server {
    	listen 80;
    	server_name my-chronicles.net www.my-chronicles.net;

    	set $server_ip $server_addr;

    	# Location block for the root (/) path
    	location / {
    	proxy_pass http://$server_ip:3000;
    	proxy_http_version 1.1;
    	proxy_set_header Upgrade $http_upgrade;
    	proxy_set_header Connection 'upgrade';
    	proxy_set_header Host $host;
    	proxy_cache_bypass $http_upgrade;
    	}

    	# Location block for the /api/ path
    	location /api/ {
    	# Remove the /api/ prefix before forwarding to the backend
    	rewrite ^/api/(.*) /$1 break;

    	# Forward requests to the backend service
    	proxy_pass http://$server_ip:5000;
    	proxy_http_version 1.1;
    	proxy_set_header Upgrade $http_upgrade;
    	proxy_set_header Connection 'upgrade';
    	proxy_set_header Host $host;
    	proxy_cache_bypass $http_upgrade;
    	}
}
