// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyChroniclesApi.Services;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyChroniclesApi.Migrations
{
    [DbContext(typeof(MyChroniclesDbContext))]
    [Migration("20241123173044_ValidUrlsTable")]
    partial class ValidUrlsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MyChroniclesApi.Models.Chronicles.AlternativeTitles", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("alternative_title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("chronicle_id")
                        .HasColumnType("uuid");

                    b.Property<string>("entertainment_category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isUnique")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.HasIndex("chronicle_id");

                    b.ToTable("AlternativeTitles");
                });

            modelBuilder.Entity("MyChroniclesApi.Models.Chronicles.Character", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("abilities")
                        .HasColumnType("text");

                    b.Property<string>("about")
                        .HasColumnType("text");

                    b.Property<int?>("age")
                        .HasColumnType("integer");

                    b.Property<string>("appearance")
                        .HasColumnType("text");

                    b.Property<string>("background")
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("personality")
                        .HasColumnType("text");

                    b.Property<string>("social_connections")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("MyChroniclesApi.Models.Chronicles.ChronicleUrlMatch", b =>
                {
                    b.Property<string>("url")
                        .HasColumnType("text");

                    b.Property<Guid>("chronicle_id")
                        .HasColumnType("uuid");

                    b.HasKey("url");

                    b.HasIndex("chronicle_id");

                    b.ToTable("ChronicleUrlMatch");
                });

            modelBuilder.Entity("MyChroniclesApi.Models.Chronicles.Chronicles", b =>
                {
                    b.Property<Guid>("chronicle_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("author")
                        .HasColumnType("text");

                    b.Property<string>("country")
                        .HasColumnType("text");

                    b.Property<DateTime?>("db_add_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("detailed_summary")
                        .HasColumnType("text");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("entertainment_category")
                        .HasColumnType("text");

                    b.Property<float?>("episodes")
                        .HasColumnType("real");

                    b.Property<string[]>("genres")
                        .HasColumnType("text[]");

                    b.Property<string>("language")
                        .HasColumnType("text");

                    b.Property<string>("length")
                        .HasColumnType("text");

                    b.Property<int?>("members")
                        .HasColumnType("integer");

                    b.Property<float?>("rating")
                        .HasColumnType("real");

                    b.Property<DateTime?>("start_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.Property<string>("synopsis")
                        .HasColumnType("text");

                    b.Property<string[]>("tags")
                        .HasColumnType("text[]");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("chronicle_id");

                    b.ToTable("Chronicles");
                });

            modelBuilder.Entity("MyChroniclesApi.Models.Chronicles.ChroniclesCast", b =>
                {
                    b.Property<Guid>("chronicle_id")
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<Guid>("character_id")
                        .HasColumnType("uuid")
                        .HasColumnOrder(0);

                    b.Property<string>("notes")
                        .HasColumnType("text");

                    b.HasKey("chronicle_id", "character_id");

                    b.HasIndex("character_id");

                    b.ToTable("ChroniclesCast");
                });

            modelBuilder.Entity("MyChroniclesApi.Models.Logs.ChronicleChanges", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string[]>("alt_titles")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("author")
                        .HasColumnType("text");

                    b.Property<string>("category")
                        .HasColumnType("text");

                    b.Property<string>("country")
                        .HasColumnType("text");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("episodes")
                        .HasColumnType("real");

                    b.Property<string[]>("genres")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("length")
                        .HasColumnType("text");

                    b.Property<string[]>("other_creators")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("start_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.Property<string>("synopsis")
                        .HasColumnType("text");

                    b.Property<string[]>("tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("ChronicleChanges");
                });

            modelBuilder.Entity("MyChroniclesApi.Models.Logs.ChronicleEditsLog", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("changed_dataid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("chronicle_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("date_of_action")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("changed_dataid");

                    b.ToTable("ChronicleEditsLog");
                });

            modelBuilder.Entity("MyChroniclesApi.Models.Urls.DecipherUrlSteps", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("chronicle_info_category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("step_number")
                        .HasColumnType("integer");

                    b.Property<string>("word_end")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("word_end_adjustment")
                        .HasColumnType("integer");

                    b.Property<int>("word_end_index")
                        .HasColumnType("integer");

                    b.Property<string>("word_start")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("word_start_adjustment")
                        .HasColumnType("integer");

                    b.Property<int>("word_start_index")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("domain");

                    b.ToTable("DecipherUrlSteps");
                });

            modelBuilder.Entity("MyChroniclesApi.Models.Urls.DomainDecipher", b =>
                {
                    b.Property<string>("domain")
                        .HasColumnType("text");

                    b.Property<DateTime>("date_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("decipher_method")
                        .HasColumnType("text");

                    b.HasKey("domain");

                    b.ToTable("DomainDeciphers");
                });

            modelBuilder.Entity("MyChroniclesApi.Models.Urls.ValidUrls", b =>
                {
                    b.Property<string>("regex_url")
                        .HasColumnType("text");

                    b.HasKey("regex_url");

                    b.ToTable("ValidUrls");
                });

            modelBuilder.Entity("MyChroniclesApi.Models.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("account_creation_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("avg_rating")
                        .HasColumnType("real");

                    b.Property<string>("bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("last_online")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("num_watched_read")
                        .HasColumnType("integer");

                    b.Property<string>("preferred_language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("primary_sort_by")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("secondary_sort_by")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MyChroniclesApi.Models.Users.UserChronicles", b =>
                {
                    b.Property<string>("user_id")
                        .HasColumnType("text");

                    b.Property<Guid>("book_id")
                        .HasColumnType("uuid");

                    b.Property<string>("entertainment_category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float?>("episode")
                        .HasColumnType("real");

                    b.Property<DateTime>("last_read")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("notes")
                        .HasColumnType("text");

                    b.Property<bool>("private_review")
                        .HasColumnType("boolean");

                    b.Property<float?>("rating")
                        .HasColumnType("real");

                    b.Property<string>("review")
                        .HasColumnType("text");

                    b.Property<DateTime?>("review_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.HasKey("user_id", "book_id");

                    b.HasIndex("book_id");

                    b.ToTable("UserChronicles");
                });

            modelBuilder.Entity("MyChroniclesApi.Models.Users.UserHistory", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("chapter")
                        .HasColumnType("integer");

                    b.Property<DateTime>("date_of_action")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("UserHistory");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MyChroniclesApi.Models.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MyChroniclesApi.Models.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyChroniclesApi.Models.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MyChroniclesApi.Models.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyChroniclesApi.Models.Chronicles.AlternativeTitles", b =>
                {
                    b.HasOne("MyChroniclesApi.Models.Chronicles.Chronicles", "chronicles")
                        .WithMany()
                        .HasForeignKey("chronicle_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("chronicles");
                });

            modelBuilder.Entity("MyChroniclesApi.Models.Chronicles.ChronicleUrlMatch", b =>
                {
                    b.HasOne("MyChroniclesApi.Models.Chronicles.Chronicles", "chronicles")
                        .WithMany()
                        .HasForeignKey("chronicle_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("chronicles");
                });

            modelBuilder.Entity("MyChroniclesApi.Models.Chronicles.ChroniclesCast", b =>
                {
                    b.HasOne("MyChroniclesApi.Models.Chronicles.Character", "characters")
                        .WithMany()
                        .HasForeignKey("character_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyChroniclesApi.Models.Chronicles.Chronicles", "chronicles")
                        .WithMany()
                        .HasForeignKey("chronicle_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("characters");

                    b.Navigation("chronicles");
                });

            modelBuilder.Entity("MyChroniclesApi.Models.Logs.ChronicleEditsLog", b =>
                {
                    b.HasOne("MyChroniclesApi.Models.Logs.ChronicleChanges", "changed_data")
                        .WithMany()
                        .HasForeignKey("changed_dataid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("changed_data");
                });

            modelBuilder.Entity("MyChroniclesApi.Models.Urls.DecipherUrlSteps", b =>
                {
                    b.HasOne("MyChroniclesApi.Models.Urls.DomainDecipher", "domain_deciphers")
                        .WithMany()
                        .HasForeignKey("domain")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("domain_deciphers");
                });

            modelBuilder.Entity("MyChroniclesApi.Models.Users.UserChronicles", b =>
                {
                    b.HasOne("MyChroniclesApi.Models.Chronicles.Chronicles", "chronicles")
                        .WithMany()
                        .HasForeignKey("book_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyChroniclesApi.Models.Users.User", "users")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("chronicles");

                    b.Navigation("users");
                });

            modelBuilder.Entity("MyChroniclesApi.Models.Users.UserHistory", b =>
                {
                    b.HasOne("MyChroniclesApi.Models.Users.User", "users")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
