const genres: string[] = [
    "Action",
    "Adventure",
    "Animation",
    "Anthology",
    "Biography",
    "Children",
    "Comedy",
    "Crime",
    "Dance",
    "Disaster",
    "Documentary",
    "Drama",
    "Epic",
    "Family",
    "Fantasy",
    "Film Noir",
    "Historical",
    "Horror",
    "Independent",
    "LGBTQ+",
    "Martial Arts",
    "Musical",
    "Mystery",
    "Parody",
    "Philosophical",
    "Political",
    "Psychological",
    "Romance",
    "Satire",
    "Sci-Fi",
    "Short",
    "Slice of Life",
    "Sports",
    "Spy",
    "Superhero",
    "Supernatural",
    "Thriller",
    "Urban",
    "War",
    "Western"
];

const tags: string[] = [
    "Action", "Adventure", "Alchemy", "Alternate History", "Alternate Universe", "Ambition",
    "Ancient Times", "Angst", "Anti-Hero", "Apocalypse", "Artificial Intelligence", "Assassins",
    "Betrayal", "Bloodlines", "Body Swap", "Bounty Hunters", "Brothers", "Business Management",
    "Cunning Protagonist", "Cultivation", "Cyberpunk", "Dark Fantasy", "Demons", "Detective",
    "Dimensional Travel", "Diplomacy", "Divine Protection", "Doppelgänger", "Dragons",
    "Dungeons", "Dystopia", "Eldritch Horror", "Elves", "Empires", "Epic Battles", "Espionage",
    "Evil Organizations", "Exploration", "Family Drama", "Fantasy World", "Fated Lovers",
    "Fate", "Futuristic", "Game Elements", "Gods", "Gore", "Gourmet", "Guilds", "Harem",
    "Healing", "Heavenly Tribulation", "Heist", "Heroes", "Hidden Abilities", "Historical",
    "Horror", "Immortals", "Incest", "Industrialization", "Intelligent Protagonist", "Inventions",
    "Isekai", "Kingdom Building", "LGBTQ+", "Lost Civilization", "Love Triangle", "Magic",
    "Magical Artifacts", "Magical Beasts", "Male Lead", "Manipulative Characters", "Martial Arts",
    "Mature Protagonist", "Mecha", "Medieval", "Mind Control", "Monsters", "Mystery",
    "Mythology", "Necromancy", "Noble Families", "Non-Human Protagonist", "Occult",
    "Overpowered Protagonist", "Parallel Worlds", "Pirates", "Political Intrigue", "Post-Apocalypse",
    "Psychological", "R18", "Rebirth", "Reincarnation", "Revenge", "Romance", "Royalty",
    "Ruthless Protagonist", "Samurai", "Schemes", "School Life", "Science Fiction", "Secret Identity",
    "Seers", "Sentient Weapons", "Serial Killers", "Shape Shifters", "Shapeshifting", "Shounen",
    "Sibling Rivalry", "Slice of Life", "Slow Growth", "Smart MC", "Soulmates", "Space Exploration",
    "Special Abilities", "Spies", "Steampunk", "Strategy", "Strong Female Lead", "Strong to Stronger",
    "Supernatural", "Survival", "Sword and Sorcery", "Swordplay", "Systems", "Talented Protagonist",
    "Technological Gap", "Telepathy", "Time Loop", "Time Manipulation", "Time Travel", "Tournament",
    "Transmigration", "Treasure Hunting", "Underdog", "Urban Fantasy", "Vampires", "Virtual Reality",
    "War", "Weak to Strong", "Weapon Mastery", "Werewolves", "Witches", "Wizards", "World Building",
    "World Travel", "Wuxia", "Yandere", "Yuri", "Zombies", "Artificial Life", "Astral Projection",
    "Battle School", "Body Tempering", "Character Development", "Clones", "Comedy", "Contracts",
    "Curses", "Dark Magic", "Deities", "Desolate Wastelands", "Doppelgängers", "Elemental Magic",
    "Empathy", "Evil Protagonist", "Explosives", "Fairy Tales", "Far Future", "Found Family",
    "Fugitives", "Genetic Engineering", "Ghosts", "Gladiators", "Holograms", "Honor", "Hypnosis",
    "Illusions", "Immortality", "Incubus", "Invisibility", "Journey", "Karma", "Legendary Weapons",
    "Liches", "Lost Technology", "Malevolent Spirits", "Martial Spirits", "Memories", "Metamorphosis",
    "Monarchies", "Monsters Taming", "Multiple Timelines", "Nanotechnology", "Nature Magic",
    "Parallel Timelines", "Planar Travel", "Possession", "Prophesies", "Psychic Abilities",
    "Puppeteers", "Quantum Mechanics", "Raising an Army", "Relics", "Resurrection", "Rune Magic",
    "Scavenging", "Secret Realms", "Shadow Magic", "Shape Shifters", "Shapeshifting", "Simulation",
    "Sky Cities", "Soul Eater", "Souls", "Space Battles", "Stellar Magic", "Summoning", "Symbiosis",
    "Teleportation", "Underworld", "Universal Travel", "Villainous Protagonist", "Weapon Creation",
    "Wuxia"
];

export default {tags, genres};