POST http://localhost:5172/urls 
Content-Type: application/json

{
    "domain": "mangadex.org",
    "decipher_method": ["title", "title", "title"],
    "title_start_end": [
        ["-", 1, 2, "-", 1, -1]
    ],
    "chapter_start_end": [
        ["Chapter", 1, 8, "-", 1, -1]
    ],
    "entertainment_category": [
        ["Graphic Novel", -2, -2, "Graphic Novel", -2, -2]
    ]
}

