POST http://localhost:5172/urls 
Content-Type: application/json

{
    "domain": "asuracomic.net",
    "decipher_method": ["url", "url", "url"],
    "title_start_end": [  
        ["/", 0, "-chapter", 0],
        ["-", 1, " ", 0]
    ],
    "chapter_start_end": [  
        ["chapter-", 8, "/", -1],
        ["", 0, "-", 0]
    ],
    "entertainment_category": [
        ["Graphic Novel", -2, "Graphic Novel", -2]
    ]
}