PUT http://localhost:5172/urls 
Content-Type: application/json

{
    "Domain": "chapmanganato.to",
    "Title_start_end": [  
        ["Chapter", 0, 1]
    ],
    "Chapter_start_end": [  
        ["Chapter", 1, -1],
        [" ", 0, 1]
    ],
    "Entertainment_category": [
        ["Graphic Novel", 0, 0]
    ],
    "Selection_type": "title",
    "dom_selector": [
        "tag",
        "title",
        0
    ]
}